# -*- coding: utf-8 -*-
"""Data Preparation (Knowledge Base)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mSN7yi9JS_dT06cEWUtDKTOGhsrwMRtq
"""

# Step 2: Data Preparation (Knowledge Base)

# For this example, we'll create a simple text file as our knowledge base.
# In a real project, this would be loaded from your policy documents, product FAQs, etc.
# You can upload your actual files to Colab or mount Google Drive.

knowledge_base_content = """
# BharatHelp Policy and Product Information

## General Information
BharatHelp is a multilingual AI chatbot designed to assist users with various queries related to our products and services. It supports English, Hindi, and Hinglish. Our goal is to provide accurate and timely information to enhance customer satisfaction.

## Product A: BharatConnect
BharatConnect is our flagship internet service offering high-speed broadband.
Plans available:
- Basic: 50 Mbps, unlimited data, ₹500/month.
- Standard: 100 Mbps, unlimited data, ₹800/month, includes free router.
- Premium: 200 Mbps, unlimited data, ₹1200/month, includes free router and premium support.
Installation typically takes 2-3 business days after subscription.
Technical support is available 24/7 via chat and phone.

## Product B: BharatMobile
BharatMobile offers affordable mobile plans with excellent network coverage.
Plans available:
- Starter: 10 GB data, unlimited calls, ₹250/month.
- Pro: 30 GB data, unlimited calls, 100 SMS, ₹400/month.
- Family: 100 GB data (shareable), unlimited calls, 200 SMS, ₹800/month (up to 4 members).
SIM card activation takes approximately 1 hour.
For international roaming, please visit our website or contact customer service.

## Customer Support
For any issues, you can contact our customer support team.
- Phone: 1800-123-4567 (toll-free)
- Email: support@bharathelp.com
- Chat: Available on our website (bharathelp.com/chat)
Our support hours are Monday to Friday, 9 AM to 6 PM IST, for general inquiries. Technical support for BharatConnect is 24/7.

## Refund Policy
Refunds for services are processed within 7-10 business days. To initiate a refund, please provide your subscription ID and reason for cancellation. A pro-rata refund will be issued for partial usage periods.

## Hindi Content Example
नमस्ते! भारतहेल्प में आपका स्वागत है। हम आपकी मदद करने के लिए यहाँ हैं।
भारतकनेक्ट हमारी हाई-स्पीड ब्रॉडबैंड सेवा है।
भारतमोबाइल के प्लान्स बहुत किफायती हैं।
किसी भी जानकारी के लिए हमारी सहायता टीम से संपर्क करें।
धन्यवाद!
"""

# Save the content to a file
knowledge_base_file = "knowledge_base.txt"
with open(knowledge_base_file, "w", encoding="utf-8") as f:
    f.write(knowledge_base_content)

print(f"Knowledge base saved to {knowledge_base_file}")

# Load the document
loader = TextLoader(knowledge_base_file, encoding="utf-8")
documents = loader.load()
print(f"Loaded {len(documents)} document(s) from {knowledge_base_file}")

# Split the document into smaller chunks for better retrieval
# This helps in retrieving more precise information
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000,
    chunk_overlap=200,
    length_function=len,
    add_start_index=True,
)
texts = text_splitter.split_documents(documents)
print(f"Split into {len(texts)} chunks.")

# Display a few chunks to verify
print("\nFirst 2 chunks:")
for i, chunk in enumerate(texts[:2]):
    print(f"--- Chunk {i+1} (length: {len(chunk.page_content)}) ---")
    print(chunk.page_content)
    print("--------------------------------------------------")

print("\nData preparation complete.")