# -*- coding: utf-8 -*-
"""Environment Setup in Google Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12LBIhvWoGJ9nH0khFz4ypr01VCrzYmTp
"""

# Step 1: Environment Setup in Google Colab

# Install necessary libraries.
# This might take a few minutes.
# We'll use the latest versions for compatibility.

print("Installing required libraries...")

!pip install -q langchain openai chromadb pydub tiktoken transformers accelerate bitsandbytes sentence-transformers optimum
!pip install -q git+https://github.com/openai/whisper.git

print("Libraries installed successfully!")

# Import necessary modules
import os
from langchain.document_loaders import TextLoader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma
from langchain.chat_models import ChatOpenAI
from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
import whisper
from pydub import AudioSegment
from pydub.playback import play # For testing audio playback if needed (Colab limitations apply)

# Set your OpenAI API key.
# IMPORTANT: Replace "YOUR_OPENAI_API_KEY" with your actual API key.
# For security, never hardcode your API key in production code or commit it to public repositories.
# In Colab, you can also use `from google.colab import userdata` and `os.environ["OPENAI_API_KEY"] = userdata.get('OPENAI_API_KEY')`
# if you've saved it as a secret.
os.environ["OPENAI_API_KEY"] = "YOUR_OPENAI_API_KEY"

# Verify API key is set (optional)
if os.getenv("OPENAI_API_KEY"):
    print("OpenAI API key loaded successfully.")
else:
    print("WARNING: OpenAI API key not set. Please set it before proceeding.")

print("\nEnvironment setup complete. Ready for the next steps!")